### ISSUE TITLE
Casting decimal to double when comparing decimal values

### ISSUE THREAD

**Issue by Xephyz** [atc-net/atc#242]
The `decimal` type is a floating-point value type taking up 16 bits, whereas the `double` type only uses 8 bits. ([See also MS Docs on floating-point numeric types](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/floating-point-numeric-types))

This means that casting the `decimal` type to `double` to compare the two values, as is done in the `DecimalExtensions` class, could potentially return a wrong answer if the values are close enough that only the decimal version can tell the difference.

Code referenced can be found here:
https://github.com/atc-net/atc/blob/32582e238083638a7f12fbe5ed571d1e7865759a/src/Atc/Extensions/BaseTypes/DecimalExtensions.cs#L17-L20

Also the same problem applies to the overloaded method call here:
https://github.com/atc-net/atc/blob/32582e238083638a7f12fbe5ed571d1e7865759a/src/Atc/Extensions/BaseTypes/DecimalExtensions.cs#L30-L38

**Comment by davidkallesen** [comment]
Fixed in https://github.com/atc-net/atc/pull/245/commits/873931176fff07b8cdd7b7262d476ac613d2d4f8
