### ISSUE TITLE
DoubleExtensions - Value of `DoubleEpsilon` is incorrect.

### ISSUE THREAD

**Issue by Xephyz** [atc-net/atc#243]
The value defined in the `DoubleExtensions` class called `DoubleEpsilon` is set to `2.2204460492503131E-15`, but this value seems to be off by 1 according to [microsoft docs found here](https://docs.microsoft.com/en-us/cpp/c-language/limits-on-floating-point-constants?view=msvc-170), saying the value is actually `2.2204460492503131E-16` (Difference being the `E-15` -> `E-16`).

I would have created a PR for this change, however I also noticed that this number is not the same as the number in the dotnet world ([Microsoft Reference on Double.Epsilon found here](https://docs.microsoft.com/en-us/dotnet/api/System.Double.Epsilon?view=netstandard-2.1))

So before creating a PR, I'm wondering if there even is a need for this value at all, since there is a built-in version in the language, which the code even uses [here](https://github.com/atc-net/atc/blob/32582e238083638a7f12fbe5ed571d1e7865759a/src/Atc/Extensions/BaseTypes/DoubleExtensions.cs#L24) - just below the definition of the `DoubleEpsilon`?

Code referenced found here:
https://github.com/atc-net/atc/blob/32582e238083638a7f12fbe5ed571d1e7865759a/src/Atc/Extensions/BaseTypes/DoubleExtensions.cs#L12

**Comment by davidkallesen** [comment]
Fixed in https://github.com/atc-net/atc/pull/245/commits/0d8f8f62d0c1e2f82e61641acd5dc0e36b2e58d2
