### ISSUE TITLE
Library with common test helper classes for (AutoNSubstituteData, etc.)

### ISSUE THREAD

**Issue by MrAndersPedersen** [atc-net/atc#51]
Så der ikke er afhængigheder til andre API's. Bare minimums

Ricky

Her er lidt info til hvor der skal udvides :-)
https://github.com/atc-net/atc/tree/master/src/Atc.XUnit

**Comment by davidkallesen** [comment]
Repository is created: https://github.com/atc-net/atc-test

**Comment by MrAndersPedersen** [comment]
@rickykaare will follow up on a few things, but the issue is closed.
