### ISSUE TITLE
Package lifecycle strategy

### ISSUE THREAD

**Issue by MrAndersPedersen** [atc-net/atc#52]
---
ATC-repo project splitning and github actions/workflows (get rid of DevOps)
---
Improve release notes for ATC.
---
Allow external github PR

Chris, Egil, Per, David

**Comment by perkops** [comment]
Solved for the following repositories:

- atc
- atc-rest-api-generator
- atc-coding-rules

Missing

- atc-cosmos-eventstore
- atc-autoformatter

**Comment by MrAndersPedersen** [comment]
@egil We would like a proposal for a release note process.
